language: go
go:
  - 1.11.3
script: "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: pZhrVAoSBj7lTLyFiprRN1tPOXNNTPuweDwNfDUNb3MLQNTN2dWUMvXAikbILgR8K4UgS1/lGYisl+8npMVudaNAPqrxQ8Cb48EViokBigEfj+uZA0aJSvZGlgSl9NOOVAu79iupSj6dAC0n4KLS6l8lHD9Sy1HDiOH5stAwOCz4HvB9wSbu93g0oH8ND0XBOmHkLVJXdn9SBPlAGprBRO0Oiywab5N/EE/WYXCHYE1tnPRHJA01hfHYzr3u0MhYsjPqHxMiKp/FSgPKmaUDmSRKq6wYRGDLJK8mtPdRXQGIhft/vQnbuwT0mNYajqvj4h014qz/ae94VoLqanRdq4xZ9YD9i2/aVsqO74UBAzCOxEXvoTDPAqPBO0zNk5sx2KxSBoKjQ1th6D9B/IpN9y3NsCZh7+RIjWX526xaqlq8DA/gRc+5YCkEjQCZgkdQqxHXZ9lznjVK4xsZYJtjkTknhEhm++GJXoicYhmp35tNX0F5ZBcCJ12gh8wsextlNR6/yF1NYPnfM/ZB+Z5bw2oC5BpMCh+rvw40jhmB+MyasCUdzOkrY/iQa5Jvfp0wx8s9hFHPowBxfigsMqLwdCLAg/Ph3hPe3cMVduoVo9tnrDuDtWy9iVAJUmW0TMPnvZyiGgwc1cqKwbPVXqTq0ROF4y3hB2zrIEuKDSkFhkw=
  file_glob: true
  file: dist/*.tar.gz
  skip_cleanup: true
  on:
    repo: kadaan/acurite_exporter
    tags: true